#!/bin/bash
set -e

echo "=============================================="
echo "   Monitor-batt - Fix 3 Níveis de Voz"
echo "=============================================="
echo ""

cd "$(dirname "$0")"

if [ ! -f "app/src/main/res/layout/activity_main.xml" ]; then
    echo "❌ Erro: Não encontrei o projeto Monitor-batt aqui."
        echo "   Coloque este script dentro da pasta Monitor-batt e rode novamente."
            exit 1
            fi
            
            echo "1. Fazendo backup dos arquivos atuais..."
            BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
            cp app/src/main/res/layout/activity_main.xml "app/src/main/res/layout/activity_main.xml.bak.$BACKUP_DATE" 2>/dev/null || true
            echo "   ✓ Backup salvo com data $BACKUP_DATE"
            
            echo ""
            echo "2. Removendo qualquer seção quebrada anterior de 'Níveis de Voz'..."
            sed -i '/3 NÍVEIS DE VOZ CONFIGURÁVEIS/,/seekVoiceVeryLow/d' app/src/main/res/layout/activity_main.xml 2>/dev/null || true
            echo "   ✓ Seção quebrada removida (se existia)"
            
            echo ""
            echo "3. Criando arquivo com o bloco CORRETO para colar..."
            cat > 3-niveis-de-voz.xml << 'BLOCKEOF'
            <!-- ==================== 3 NÍVEIS DE VOZ CONFIGURÁVEIS ==================== -->
            <TextView
                android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                        android:text="Níveis de Voz (configuráveis)"
                            android:textColor="#A0C4E2"
                                android:textSize="14sp"
                                    android:layout_marginTop="20dp"
                                        android:layout_marginBottom="8dp"
                                            android:paddingStart="4dp" />
                                            
                                            <!-- Voz Baixa -->
                                            <LinearLayout
                                                android:layout_width="match_parent"
                                                
                                                    android:layout_height="wrap_content"
                                                        android:orientation="horizontal"
                                                            android:gravity="center_vertical"
                                                                android:paddingStart="4dp"
                                                                    android:paddingEnd="4dp">
                                                                    
                                                                        <TextView
                                                                                android:layout_width="0dp"
                                                                                        android:layout_height="wrap_content"
                                                                                                android:layout_weight="1"
                                                                                                        android:text="Voz Baixa"
                                                                                                                android:textColor="#FFFFFF"
                                                                                                                        android:textSize="15sp" />
                                                                                                                        
                                                                                                                            <TextView
                                                                                                                                    android:id="@+id/tvVoiceLowValue"
                                                                                                                                            android:layout_width="wrap_content"
                                                                                                                                                    android:layout_height="wrap_content"
                                                                                                                                                            android:text="10%"
                                                                                                                                                                    android:textColor="#3F9EF0"
                                                                                                                                                                            android:textStyle="bold"
                                                                                                                                                                                    android:textSize="15sp" />
                                                                                                                                                                                    </LinearLayout>
                                                                                                                                                                                    
                                                                                                                                                                                    <SeekBar
                                                                                                                                                                                        android:id="@+id/seekVoiceLow"
                                                                                                                                                                                            android:layout_width="match_parent"
                                                                                                                                                                                                android:layout_height="wrap_content"
                                                                                                                                                                                                    android:max="80"
                                                                                                                                                                                                        android:paddingStart="4dp"
                                                                                                                                                                                                            android:paddingEnd="4dp" />
                                                                                                                                                                                                            
                                                                                                                                                                                                            <!-- Voz Crítica -->
                                                                                                                                                                                                            <LinearLayout
                                                                                                                                                                                                                android:layout_width="match_parent"
                                                                                                                                                                                                                    android:layout_height="wrap_content"
                                                                                                                                                                                                                        android:orientation="horizontal"
                                                                                                                                                                                                                            android:gravity="center_vertical"
                                                                                                                                                                                                                                android:layout_marginTop="12dp"
                                                                                                                                                                                                                                    android:paddingStart="4dp"
                                                                                                                                                                                                                                        android:paddingEnd="4dp">
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            <TextView
                                                                                                                                                                                                                                                    android:layout_width="0dp"
                                                                                                                                                                                                                                                            android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                    android:layout_weight="1"
                                                                                                                                                                                                                                                                            android:text="Voz Crítica"
                                                                                                                                                                                                                                                                                    android:textColor="#FFFFFF"
                                                                                                                                                                                                                                                                                            android:textSize="15sp" />
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                <TextView
                                                                                                                                                                                                                                                                                                        android:id="@+id/tvVoiceCriticalValue"
                                                                                                                                                                                                                                                                                                                android:layout_width="wrap_content"
                                                                                                                                                                                                                                                                                                                        android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                android:text="5%"
                                                                                                                                                                                                                                                                                                                                        android:textColor="#3F9EF0"
                                                                                                                                                                                                                                                                                                                                                android:textStyle="bold"
                                                                                                                                                                                                                                                                                                                                                        android:textSize="15sp" />
                                                                                                                                                                                                                                                                                                                                                        </LinearLayout>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <SeekBar
                                                                                                                                                                                                                                                                                                                                                            android:id="@+id/seekVoiceCritical"
                                                                                                                                                                                                                                                                                                                                                                android:layout_width="match_parent"
                                                                                                                                                                                                                                                                                                                                                                    android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                        android:max="80"
                                                                                                                                                                                                                                                                                                                                                                            android:paddingStart="4dp"
                                                                                                                                                                                                                                                                                                                                                                                android:paddingEnd="4dp" />
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                <!-- Voz Quase Acabando -->
                                                                                                                                                                                                                                                                                                                                                                                <LinearLayout
                                                                                                                                                                                                                                                                                                                                                                                    android:layout_width="match_parent"
                                                                                                                                                                                                                                                                                                                                                                                        android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                                            android:orientation="horizontal"
                                                                                                                                                                                                                                                                                                                                                                                                android:gravity="center_vertical"
                                                                                                                                                                                                                                                                                                                                                                                                    android:layout_marginTop="12dp"
                                                                                                                                                                                                                                                                                                                                                                                                        android:paddingStart="4dp"
                                                                                                                                                                                                                                                                                                                                                                                                            android:paddingEnd="4dp">
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                <TextView
                                                                                                                                                                                                                                                                                                                                                                                                                        android:layout_width="0dp"
                                                                                                                                                                                                                                                                                                                                                                                                                                android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                                                                                        android:layout_weight="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                android:text="Voz Quase Acabando"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        android:textColor="#FFFFFF"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                android:textSize="15sp" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TextView
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            android:id="@+id/tvVoiceVeryLowValue"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    android:layout_width="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    android:text="2%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            android:textColor="#3F9EF0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    android:textStyle="bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            android:textSize="15sp" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </LinearLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <SeekBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                android:id="@+id/seekVoiceVeryLow"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    android:layout_width="match_parent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        android:layout_height="wrap_content"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            android:max="80"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                android:paddingStart="4dp"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    android:paddingEnd="4dp" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BLOCKEOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "   ✓ Arquivo '3-niveis-de-voz.xml' criado na raiz do projeto"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "=============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "PRÓXIMOS PASSOS:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "=============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "1. Abra o layout:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "   nano app/src/main/res/layout/activity_main.xml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "2. Procure pela linha que contém 'seekInterval'"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "3. Cole o conteúdo do arquivo '3-niveis-de-voz.xml' logo DEPOIS"
                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "   do </SeekBar> do intervalo, mas ainda DENTRO do LinearLayout/CardView"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "4. Salve (Ctrl+O → Enter → Ctrl+X)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "5. Teste o build:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "   ./gradlew clean assembleDebug"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "=============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SCRIPT_EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    chmod +x fix-voice-levels.sh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "✅ Script criado com sucesso!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
