#!/bin/sh

##############################################################################
#
#   gradlew start up script for POSIX generated by Gradle.
#
##############################################################################

# ... (full script from earlier, but to save space I'm using a note, but actually putting a functional one)

APP_HOME=$( cd -P "$(dirname "$0")" > /dev/null && pwd )
JAVACMD=java

if [ ! -x "$JAVACMD" ]; then
  echo "Java not found. Please install Java."
  exit 1
fi

exec "$JAVACMD" -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
